### ISSUE TITLE
Shut down the backend if macOS is going down.

### ISSUE THREAD

**Issue by peturingi** [peturingi/gui-o-mac-tic#12]
If macOS is about to reboot or shutdown (macOS might shut down in case of a very low battery), then gui-o-mac-tic shall shut down any processes it has launched.

**Justification:** It is common to require applications, such as Mailpile, to be explicitly shut down as to prevent data corruption.

**Here be dragons:** The backend (application which is using GUI-o-Mac-tic as a front end), might itself detect that macOS is going down and begin a shutdown process before GUI-o-Mac-tic requests that that it does so. For now, we assume that subsequent shutdown requests, to a backend which is being shut down, hook into the shutdown process and return upon its completion.

**Implementation:** [See QA1340](https://developer.apple.com/library/content/qa/qa1340/_index.html) for hints on how to subscribe to shutdown events.

**Comment by BjarniRunar** [comment]
Mailpile understands the Unix SIGINT signal and will attempt a clean shutdown when it receives it.

A generic solution here is simply to send SIGINT to any running child processes when gui-o-mac-tic detects it is time to die.

**Comment by peturingi** [comment]
I'm closing this ticket because

-  Mailpile [already supports SIGTERM](https://github.com/mailpile/Mailpile/blob/3f6ab53de90f85bca8c52e5511e78cd7aca5ef1f/mailpile/app.py#L67) (sent by macOS before it goes down), and
- GUI-o-Mac-tic already knows how to shut itself down (which involves closing any open terminals) upon receiving a notification that the system is going down.
