### ISSUE TITLE
Opened Terminal.app tabs and windows are not quit when GUI-o-Mac-tic quits.

### ISSUE THREAD

**Issue by peturingi** [peturingi/gui-o-mac-tic#13]
GUI-o-Mac-tic is capable of opening Terminal.app tabs and windows.
GUI-o-Mac-tic shall clean up after itself and quit any Terminal.app tabs and windows which it has opened during its execution.

**Comment by BjarniRunar** [comment]
See comment on #12 regarding use of SIGINT to alert child processes that it is time to die. Same solution?

**Comment by peturingi** [comment]
That would be a nice solution.

Unfortunately, as of now, GUI-o-Mac-tic executes an AppleScript to launch Terminal.app. Afaik. a process which launches another by an AppleScript, does not become an ancestor of the launched process.

AppleScript is being used to launch Terminal.app only because it is easy to set the Terminal's window title that way. I rather not have to manage external processes; not using AppleScript might allow the use of SIGINT. Will look into launching Terminal.app by other means.

**Comment by BjarniRunar** [comment]
You don't need a parent/child relationship, but you do need the process ID. IIRC, any process can send any signal to any other process under the same user ID.

**Comment by peturingi** [comment]
Fixed in https://github.com/peturingi/gui-o-mac-tic/commit/df7971471bdd2a7398c9038742278a28ba28cda7.
