### ISSUE TITLE
Prevent users from running GUI-o-Mac-tic from a mounted DMG file.

### ISSUE THREAD

**Issue by peturingi** [peturingi/gui-o-mac-tic#15]
Some users are not be familiar with how to install Apps from a mounted DMG; they might think that mounting a DMG is the same as installing an app. This leads to confusion as the App _disappears_ upon deleting the DMG.

Prevent users from launching GUI-o-Mac-tic from a mounted DMG file, ideally by displaying an error message.

**Comment by BjarniRunar** [comment]
If you want to make this configurable, adding a mac-os-specific variable to the configuration syntax is an option here. It is vaguely within the realm of possibility that someone might *want* to ship a relocatable app that just runs from a DMG, even if we don't?

**Comment by peturingi** [comment]
That works for me :)

**Comment by peturingi** [comment]
Implemented in https://github.com/peturingi/gui-o-mac-tic/commit/515ae5839cb5beba373565e263ef6a4c2751671d
