### ISSUE TITLE
Spaces in C-Style arguments are incorrectly parsed

### ISSUE THREAD

**Issue by peturingi** [peturingi/gui-o-mac-tic#16]
Spaces in C-Style arguments are incorrectly parsed.

**Example:**
When using GUI-o-Mac-tic with Mailpile, Mailpile is passed the argument "--set="prefs.open_in_browser = false".
That argument specifies that Mailpile should not launch a browser as it starts up.
However, as the argument is incorrectly parsed, Mailpile does launch a browser.

**Comment by BjarniRunar** [comment]
The original intent was that the entire string be passed to a shell, and the shell handle the parsing. This is how things are specified in PROTOCOL.md. I don't think it's a great idea to re-implement all the shell argument parsing logic again.

This is not high priority for Mailpile, as we can work around this limitation at the other end if necessary.

**Comment by peturingi** [comment]
@BjarniRunar provided a fix for Mailpile in https://github.com/mailpile/Mailpile/commit/bbfe4e8e7bb6a20678e8352cd6474d8d39656a1d#diff-fd0f5fe11bca3edf81416ccfaba47810 , line 248.

**Comment by peturingi** [comment]
**For documentation purposes** I mention that the Swift API requires command arguments to be formatted in a list as a list of C-style arguments before being passed into a shell command.This is to say that "ls -l -a" will fail as the two arguments "-l -a" will be treated as a single argument.
A workaround I found is to have "env -S" take the command and its non-c-formatted argument, env then breaks the single string up into a c-style argument list before passing it to the command.

**Comment by BjarniRunar** [comment]
Hmm, FWIW, this is still not going to be in line with the protocol spec. The spec says: "Each string is passed to the operating system shell as a command to execute..."

Which means the command Swift should execute would be "/bin/sh" or "/bin/bash", with two arguments: "-c" and "whatever came from the config file as one long string".

The protocol mandating that the shell be used was deliberate, both to avoid parsing issues and to allow the caller to use shell-isms.

**Comment by BjarniRunar** [comment]
(Perhaps this is what "env -S" does, I am unfamiliar with that particular idiom.  If it does, hooray!)
