### ISSUE TITLE
GUI remains open even if Mailpile is shut down from the terminal.

### ISSUE THREAD

**Issue by peturingi** [peturingi/gui-o-mac-tic#18]
GUI-o-Mac-tic shall quit if it's backend process (such as Mailpile) is closed externally such as via a Terminal.

**Comment by BjarniRunar** [comment]
Note: the semantics of this are defined in PROTOCOL.md - EOF on the update command stream (whether that's STDIO or a socket) is a signal that GUI-o-Mac-tic should shutdown.

**Comment by peturingi** [comment]
Solved by https://github.com/peturingi/gui-o-mac-tic/commit/1868d8911ed066766c53d55b859ef06eeeff521b
