### ISSUE TITLE
Implement set_item(label=...) for main window buttons

### ISSUE THREAD

**Issue by BjarniRunar** [peturingi/gui-o-mac-tic#19]
Feel free to close if this is obsolete.

I noticed during the usability testing that the Quit button stayed labeled "Quit GUI" during the entire test, even though the backend had changed state and set a set_item() to update the text. Is it possible that updating button labels is unimplemented?

**Comment by peturingi** [comment]
I fixed that in https://github.com/peturingi/gui-o-mac-tic/commit/c0f797f05fe4e3b418f4f685422b5d051ab51c66

**Comment by BjarniRunar** [comment]
I shall refrain from opening more issues until I've played with the .app then. ;)

**Comment by peturingi** [comment]
Please open issues if you remember something which you think I might have forgotten or overlooked :)
