### ISSUE TITLE
Change task-bar icons when macOS is made to "Use dark menu bar and Dock."

### ISSUE THREAD

**Issue by peturingi** [peturingi/gui-o-mac-tic#21]
macOS can be set (System Preferences -> General) to _Use dark menu bar and Dock._ When this occurs, GUI-o-Mac-tic shall replace any icons in the _status bar_ which have been defined to have a corresponding dark-themed-version.

**Comment by peturingi** [comment]
This ticket has become more important as the next version of macOS has a special "dark"-mode which appears to be quite popular among beta-testers.

**Comment by BjarniRunar** [comment]
IIRC, the protocol actually has some support for theming of the icons, which was meant for exactly this sort of case. Grep for `theme` in https://github.com/mailpile/gui-o-matic/blob/master/PROTOCOL.md , it's near the top. Basically, if your gui-o-matic detects it needs a dark theme there is a way to communicate that.

The main question is whether the OS X themes can be shared with other platforms - for some reason I came to the conclusion that was hard in an earlier iteration, but the reasons may have been Python-API-specific. If the themes cannot be shared, then the calling app needs to define in settings all of "dark", "light", "osx" and "osx-dark" themes (if the icons can be shared we just need "light" and "dark").

**Comment by peturingi** [comment]
Thank you for the reminder about the theming support.
I'm confident that we can share graphical assets. The most difficulty I had had was to scale icons correctly for the menu bar; that I have solved.

**Comment by peturingi** [comment]
Done.
Implemented in https://github.com/peturingi/gui-o-mac-tic/commit/27cb33be3ad0771a85d8122dc7409440226cbaa0 and https://github.com/peturingi/gui-o-mac-tic/commit/022982697464afddae448a139badc30e10bae08d.
