### ISSUE TITLE
Splash screen functionality

### ISSUE THREAD

**Issue by BjarniRunar** [peturingi/gui-o-mac-tic#38]
Hello! I was looking at the splash screen in my Mac VM. It seems large, and the text message is still in the wrong place (this is a recent but not brand-new build, apologies if these are already fixed).

Is gui-o-mac-tic respecting the width and height parameters sent in the `show_splash_screen` command? I think it's just showing the full image, but the intent is that it should be scaled to match those arguments.

Similarly, the show_splash_screen command may receive message_x or message_y arguments which are floats (range 0-1). The way these are interpreted by the Python app, is the default position is (0.5, 0.5), centering the any messages within the splash screen. Altering message_x or message_y changes the relative position of the middle of the message, with the origin (0, 0) being the top left corner.

It would be great if gui-o-mac-tic implemented the same thing. Also, is the splash screen implementing font sizing and progress bars?

Mailpile's GUI currently only sends message_y=0.8, which should be interpreted as "display the message 80% of the way down the image, centered horizontally" (since message_x defaults to 0.5).

Here is a screenshot of how things look on Linux (which I am pleased with):

![screenshot-mailpile-splash](https://user-images.githubusercontent.com/3943592/45588526-9b859c80-b905-11e8-93b3-63fef7807109.jpg)

**Comment by peturingi** [comment]
![untitled](https://user-images.githubusercontent.com/1230353/45588582-418dd280-b917-11e8-8ce9-042a9555006a.png)
@BjarniRunar this is how the window appears on my machine (macOS 10.13.6). Please confirm that it appears identically on yours.

**Comment by BjarniRunar** [comment]
Yes, that is how it looks on my machine. In the VM it is actually so big (and the VM screen so small) that part of it disappears behind the dock at the bottom, so I couldn't tell if there was a progress bar or not (I see it on your screenshot).

**Comment by peturingi** [comment]
> Hello! I was looking at the splash screen in my Mac VM. It seems large, and the text message is still in the wrong place (this is a recent but not brand-new build, apologies if these are already fixed).
> 
> Is gui-o-mac-tic respecting the width and height parameters sent in the show_splash_screen command? I think it's just showing the full image, but the intent is that it should be scaled to match those arguments.
No, because the width and height arguments are not defined in https://github.com/mailpile/gui-o-matic/blob/master/PROTOCOL.md. You are correct in that gui-o-mac-tic scales the view's size to match the image's size.
> 
> Similarly, the show_splash_screen command may receive message_x or message_y arguments which are floats (range 0-1). The way these are interpreted by the Python app, is the default position is (0.5, 0.5), centering the any messages within the splash screen. Altering message_x or message_y changes the relative position of the middle of the message, with the origin (0, 0) being the top left corner.
Actually I default to 0,0 and not 0.5,0.5, I will fix that. Also, there appears to be a bug in the position handling, I will fix that. 
> 
> It would be great if gui-o-mac-tic implemented the same thing. Also, is the splash screen implementing font sizing and progress bars?
Yes, both.
> 
> Mailpile's GUI currently only sends message_y=0.8, which should be interpreted as "display the message 80% of the way down the image, centered horizontally" (since message_x defaults to 0.5).
I will fix that.

**Comment by peturingi** [comment]
> ![untitled](https://user-images.githubusercontent.com/1230353/45588582-418dd280-b917-11e8-8ce9-042a9555006a.png)
> @BjarniRunar this is how the window appears on my machine (macOS 10.13.6). Please confirm that it appears identically on yours.

Note that the screenshot appears much larger, for some reason which is unknown to me, here on github than when shown in an image browser on my computer.

**Comment by peturingi** [comment]
Solved in https://github.com/peturingi/gui-o-mac-tic/commit/a41b16d9ae4c3adbacfa0be3ca9b03aef6ef454d
