### ISSUE TITLE
Status (main) window layout and fonts

### ISSUE THREAD

**Issue by BjarniRunar** [peturingi/gui-o-mac-tic#39]
A screenshot!

![screenshot-mailpile-statuswin](https://user-images.githubusercontent.com/3943592/45588586-8a895b00-b906-11e8-9fe8-b15a571cc288.jpg)

This screenshot should show the Linux gui-o-matic next to a recent Mac gui-o-mac-tic. There are a bunch of small discrepancies - but they add up. The Linux window looks (IMO) much nicer.

The differences I see:

1. Fonts on the Mac are all quite a bit smaller
2. The vertical alignment of the titles and descriptions in each status element differ
3. The status message is between the buttons on Mac

Discussing each point further...

Fonts: It looks like you are respecting the font size requests in the JSON (including the buttons?), but the numbers appear to mean different things on different platforms. There might just be a fixed scale factor that needs to be applied in order for things to be consistent?

Alignment: The Linux gui-o-matic has the text elements packed in so that the title and description are close to each other, but together get vertically centered relative to the size available. Which is better is probably a matter of taste, but I like the Linux version better... :wink: 

Status message: Early versions on Linux had the status message between the buttons as well, but I moved it because we a) dropped one of the three status messages and b) some of the status messages were too long for the space. This is actually expressed in the JSON - the third defined status area is named "notification" which is a hint to the GUI that notifications/status messages should go there instead of the default between-the-buttons location. (I don't remember if that's in the spec, but it probably should be.)

**Comment by peturingi** [comment]
`1. Fonts on the Mac are all quite a bit smaller`
`Fonts: It looks like you are respecting the font size requests in the JSON (including the buttons?), but   the numbers appear to mean different things on different platforms. There might just be a fixed scale  factor that needs to be applied in order for things to be consistent?
`
That is because the default font size on macOS is 12 and Mailpile sets the smaller font in your screenshot to 10 which makes it small and hard to read.
You could try to set the configuration to generate a constant +2 to the font size when running on macOS?

**Comment by peturingi** [comment]
> Alignment: The Linux gui-o-matic has the text elements packed in so that the title and description are close to each other, but together get vertically centered relative to the size available. Which is better is probably a matter of taste, but I like the Linux version better... 😉
Will fix.

**Comment by peturingi** [comment]
> This is actually expressed in the JSON - the third defined status area is named "notification" which is a hint to the GUI that notifications/status messages should go there instead of the default between-the-buttons location. 
@BjarniRunar This is not clear to me. Does "instead of" imply that notification can be shown between the buttons, as is now, but can also be shown above them as in your linux screenshot?

**Comment by BjarniRunar** [comment]
Yes, that's how the Python GUI is written, the default location for notifications is between the buttons, but if the config specifies that it would RATHER use one of the status areas for notifications, that is what happens instead.

**Comment by peturingi** [comment]
> Yes, that's how the Python GUI is written, the default location for notifications is between the buttons, but if the config specifies that it would RATHER use one of the status areas for notifications, that is what happens instead.

The spec says:

> notify_user
> 
> Arguments:
> 
> message: (string) Tell the user something
> popup: (optional bool) Prefer an OSD/growl/popup style notification
> alert: (optional bool) Try harder to get the user's attention
> actions: (optional list of dicts) Actions relating to the notification

I understand you such that the following shall be added: notification: (optional bool) Place the notification, centered, at the bottom in the bottom-most status area.

**Comment by BjarniRunar** [comment]
It's just the fact that the ID is the magic string "notification."

You're right I should update the spec, but I doubt I'll get to it today.

**Comment by peturingi** [comment]
I'll implement is such that if there is a status display whose id is 'notification' then notifications will be displayed there instead of between the buttons.

**Comment by peturingi** [comment]
> The status message is between the buttons on Mac
fixed in https://github.com/peturingi/gui-o-mac-tic/commit/cf952ad2c59cf628e2d3939e37507ed08df4a7a1 and https://github.com/peturingi/gui-o-mac-tic/commit/23f9bdf588ef13b0ccce7eb9985e51a09319aa8e
