### ISSUE TITLE
Cookies are not used by GET and POST.

### ISSUE THREAD

**Issue by peturingi** [peturingi/gui-o-mac-tic#4]
Cookies specified for a host:port in stage 1 shall be sent along with GET and POST requests to that host for that port.
Cookies shall be sent along **iff** the endpoint's TCP port matches the port associated with the cookie in the stage 1 config.

This is to say that the following cookie shall be sent to an endpoint at localhost:33411 and **NOT** to an endpoint at localhost:1337.
```
"http_cookies": {
        "localhost:33411": {
            "session": "abacabadonk"
        }
    }
```

Suggested implementation points are:

- GetURL\execute(...) in GetURL.swift and
- PostURL\execute(...) in PostURL.swift

**Comment by BjarniRunar** [comment]
Note: We need to re-do how the app is shut down, and the solution will likely involve making a QUIT HTTP API request - which will need cookies to authenticate. So this is somewhat important.

**Comment by peturingi** [comment]
I removed show_url from the issue's description as the protocol specifies that cookies are not to be used by that command.

**Comment by peturingi** [comment]
Implemented in https://github.com/peturingi/gui-o-mac-tic/commit/7817134f421027af5c3d8c2378adeb2b9b186ac1.
